apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fast-walrus-dotnet-basic
  janus-idp.io/tekton: fast-walrus-dotnet-basic
  backstage.io/kubernetes-id: fast-walrus-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fast-walrus-dotnet-basic
resources: 
- deployment.yaml
- route.yaml
- service.yaml
